services:
  app:
    build:
      context: .
    container_name: fiquela-api
    expose:
      - "9000"

  web:
    image: nginx:alpine
    container_name: fiquela-web
    volumes:
      - ./config/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
