services:
  app:
    build:
      context: .
      args:
        API_TOKEN: ${API_TOKEN}
    container_name: fiquela-api
    volumes:
      - ./workspace:/app/workspace
    expose:
      - "9000"

  web:
    image: nginx:alpine
    container_name: fiquela-web
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
