services:
  app:
    build:
      context: .
      target: dev
    container_name: fiquela-api
    expose:
      - "9000"
    env_file:
      - .env
    volumes:
      - .:/app

  web:
    image: nginx:alpine
    container_name: fiquela-web
    ports:
      - "6917:80"
    volumes:
      - ./config/docker/nginx:/etc/nginx/conf.d
      - ./public:/app/public:ro
    depends_on:
      - app
