services:
  app:
    build:
      context: .
    container_name: fiquela-api
    environment:
      - API_TOKEN: ${API_TOKEN}
    expose:
      - "9000"

  web:
    image: nginx:alpine
    container_name: fiquela-web
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
